let ts = "1690871681966";
let publicKey = "1aef9fcbf8e3244d6fa7e094c2bbe2aa";
let privateKey = "e1c3b1927d8f85867e3b244d70ad9a40d4f2b7f4";
let hashVal = "aab780c9e526c338db50c331b66b4b8d";

let movieAPI = "169a56f0bcf11b541b0821f0599256f1";
let authBearer =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNjlhNTZmMGJjZjExYjU0MWIwODIxZjA1OTkyNTZmMSIsInN1YiI6IjY0YzlmYjIxMDAxYmJkMDBlODM4ZWEyMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LOwvszfRrjQ7VZ291QYKHR_xUcf-eGI7ouPwUEt37DA";

const mockData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/1wOu8rdvPxU1ObHi20VcRhfNpbo.jpg",
      genre_ids: [12, 14, 28],
      id: 10195,
      original_language: "en",
      original_title: "Thor",
      overview:
        "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
      popularity: 75.137,
      poster_path: "/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
      release_date: "2011-04-21",
      title: "Thor",
      video: false,
      vote_average: 6.768,
      vote_count: 19853,
    },
    {
      adult: false,
      backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
      genre_ids: [14, 28, 35],
      id: 616037,
      original_language: "en",
      original_title: "Thor: Love and Thunder",
      overview:
        "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
      popularity: 157.009,
      poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
      release_date: "2022-07-06",
      title: "Thor: Love and Thunder",
      video: false,
      vote_average: 6.539,
      vote_count: 6278,
    },
    {
      adult: false,
      backdrop_path: "/5wzaOqsxuXgErXEusfuE6AWtcNm.jpg",
      genre_ids: [14, 16, 878],
      id: 50388,
      original_language: "ja",
      original_title: "いばらの王 -King of Thorn-",
      overview:
        "A mysterious virus, nicknamed Medusa, is spreading around Japan, turning its victims into stone. Given the impossibility of finding an immediate cure, the government opts for cryopreserving a select group of patients until they come up with a solution. Kasumi, one of the chosen ones, has been asleep for years and her awakening, more than a bed of roses, is a bed of thorns, and happens in the midst of total chaos where monstrous creatures lie in wait all around.",
      popularity: 18.876,
      poster_path: "/wH9SSbsNWKLtZjA4LBQ7P2GwbLZ.jpg",
      release_date: "2010-05-01",
      title: "King of Thorn",
      video: false,
      vote_average: 6.609,
      vote_count: 128,
    },
    {
      adult: false,
      backdrop_path: "/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg",
      genre_ids: [28, 12, 878],
      id: 284053,
      original_language: "en",
      original_title: "Thor: Ragnarok",
      overview:
        "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
      popularity: 90.413,
      poster_path: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
      release_date: "2017-10-02",
      title: "Thor: Ragnarok",
      video: false,
      vote_average: 7.596,
      vote_count: 19349,
    },
    {
      adult: false,
      backdrop_path: "/4zTsF0RtO0av3YX1NaKDqGKPxYF.jpg",
      genre_ids: [28, 12, 14],
      id: 76338,
      original_language: "en",
      original_title: "Thor: The Dark World",
      overview:
        "Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.",
      popularity: 72.723,
      poster_path: "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
      release_date: "2013-10-30",
      title: "Thor: The Dark World",
      video: false,
      vote_average: 6.541,
      vote_count: 16204,
    },
    {
      adult: false,
      backdrop_path: "/6UwmkaB1mRZ0fo5A79m5XpVA5RK.jpg",
      genre_ids: [16, 12, 35, 10751, 14],
      id: 106631,
      original_language: "is",
      original_title: "Hetjur Valhallar - Þór",
      overview:
        "An over confident teen with a magical weapon and a handful of imperfect gods join forces against an evil queen and her army of giants",
      popularity: 8.53,
      poster_path: "/6gs0642LLTa5Nl6vUR06ZQ3stTu.jpg",
      release_date: "2011-10-14",
      title: "Legends of Valhalla: Thor",
      video: false,
      vote_average: 5.3,
      vote_count: 45,
    },
    {
      adult: false,
      backdrop_path: "/rESsefcThUTYAOX5HkRK5nTGGtj.jpg",
      genre_ids: [14, 12, 28],
      id: 183154,
      original_language: "it",
      original_title: "Thor il conquistatore",
      overview:
        "After both his parents are brutally murdered by his fathers rival Gnut and his men the new born Thor is placed in hiding by the physical embodiment of the god Teisha.  Raised in secret under the guidance of Teisha, Thor comes to maturity and goes on a quest to avenge the death of his parents and return peace to his lands, in the process he discovers a woman to take as his wife, finds and uncovers his fathers sword and masters the art of combat, all under the ever watchful eye of the amorphous Teisha.",
      popularity: 4.436,
      poster_path: "/jGvDzNyBJxaK99snuHoDEOqh5hg.jpg",
      release_date: "1983-02-05",
      title: "Thor the Conqueror",
      video: false,
      vote_average: 3.8,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/v6tInt4367fOcwNyWnPX3hIV2fL.jpg",
      genre_ids: [53],
      id: 387840,
      original_language: "es",
      original_title: "Purasangre",
      overview:
        "5 professionals rob a Horce Racetrack and a Casino Complex but when one of them makes too many mistakes, the police starts a deadliest manhunt to recover the money.",
      popularity: 5.683,
      poster_path: "/n8A7bsIrBrXYOWup6KVMWkwdGcX.jpg",
      release_date: "2016-01-13",
      title: "Thoroughbred",
      video: false,
      vote_average: 6.5,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/1RwWclnfcAcFG5n1qejtKRQDqE3.jpg",
      genre_ids: [878, 14],
      id: 76535,
      original_language: "en",
      original_title:
        "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer",
      overview:
        "Agent Coulson stops at a convenience store and deals with a coincidental robbery during his visit.",
      popularity: 17.548,
      poster_path: "/njrOqsmFH4pxBrhcoslqLfw2OGk.jpg",
      release_date: "2011-10-25",
      title:
        "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer",
      video: false,
      vote_average: 6.825,
      vote_count: 395,
    },
    {
      adult: false,
      backdrop_path: "/gseVao2FiyRZuqWQNl05BQ8TEVM.jpg",
      genre_ids: [16, 12, 10751],
      id: 14317,
      original_language: "en",
      original_title: "The Wild Thornberrys Movie",
      overview:
        "Eliza and Debbie are two sisters who don't always get along. But their relationship is put to the test when Debbie's life is in danger, and Eliza might have to give up her power to talk to animals....",
      popularity: 25.497,
      poster_path: "/nmWpcUQtWHC4kjVCygiFEDR1wCY.jpg",
      release_date: "2002-12-20",
      title: "The Wild Thornberrys Movie",
      video: false,
      vote_average: 6.444,
      vote_count: 233,
    },
    {
      adult: false,
      backdrop_path: "/1y6dEBTOzCyJRetN9fOtS0H7Vnx.jpg",
      genre_ids: [28, 16, 14, 878],
      id: 101907,
      original_language: "en",
      original_title: "Hulk vs. Thor",
      overview:
        "For ages, Odin has protected his kingdom of Asgard. But every winter, the All-Father must rest and regain his strength for one week. During this time, all of Asgard's foes (including trolls, giants, dark elves, and demons) try to claim the realm for their own, but they are always stopped by Odin's son, the mighty Thor, albeit with the loss of many brave Asgardian warriors. Loki, god of mischief, has kidnapped Dr. Bruce Banner and brought him to Asgard with the help of Amora, once Thor's lover, now the supervillain known as the Enchantress. Loki makes Banner angry and he changes into the Hulk. The Enchantress then casts a spell over the Hulk which separates Banner from his monstrous alter-ego and grants Loki control over the Hulk's body.",
      popularity: 14.483,
      poster_path: "/pezTIa0SmmNIhjQWzo63OlBdpLf.jpg",
      release_date: "2009-01-27",
      title: "Hulk vs. Thor",
      video: false,
      vote_average: 6.797,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/u42KtZj9guzNlA44jI5yLFwqI25.jpg",
      genre_ids: [27, 35],
      id: 408914,
      original_language: "ta",
      original_title: "சங்கிலி புங்கிலி கதவ தொற",
      overview:
        "A young man who wants to own a house buys a mansion and moves into it with his extended family not knowing that there is a ghost in the place.",
      popularity: 4.291,
      poster_path: "/n8PuhJJ9JjbEqsJIjz7VXhAP7N.jpg",
      release_date: "2017-05-19",
      title: "Sangili Bungili Kadhava Thorae",
      video: false,
      vote_average: 4.7,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/99Rd26ceIhonpOP5JoqcXYqnkD.jpg",
      genre_ids: [18, 53],
      id: 397722,
      original_language: "en",
      original_title: "Thoroughbreds",
      overview:
        "Two teenage girls in suburban Connecticut rekindle their unlikely friendship after years of growing apart. In the process, they learn that neither is what she seems to be, and that a murder might solve both of their problems.",
      popularity: 10.283,
      poster_path: "/pIxZzTfITqBpZxbIGsV01DcoHsT.jpg",
      release_date: "2018-03-09",
      title: "Thoroughbreds",
      video: false,
      vote_average: 6.421,
      vote_count: 1031,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 92237,
      original_language: "en",
      original_title: "Thorium Remix",
      overview:
        "How LFTR, the Liquid Fluoride Thorium Reactor, will unlock abundant clean energy stored in Earth's plentiful thorium.",
      popularity: 1.233,
      poster_path: null,
      release_date: "2011-10-01",
      title: "Thorium Remix",
      video: false,
      vote_average: 6,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/yq1Zr8mCVd0jWpoLO4u9RiUB8K7.jpg",
      genre_ids: [35, 878],
      id: 413279,
      original_language: "en",
      original_title: "Team Thor",
      overview:
        "Discover what Thor was up to during the events of Captain America: Civil War.",
      popularity: 10.813,
      poster_path: "/jVSmX89BvsQV2z3wh2IVYVNVw1a.jpg",
      release_date: "2016-08-28",
      title: "Team Thor",
      video: false,
      vote_average: 7.285,
      vote_count: 483,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 233119,
      original_language: "en",
      original_title:
        "Mesterrytteren Thorvald Ellegaard paa Cykelbanen i Ordrup",
      overview:
        "Footage of the cycling champion Thorvald Ellegaard riding in Ordrup.",
      popularity: 0.6,
      poster_path: null,
      release_date: "1913-11-04",
      title: "Master Rider Thorvald Ellegaard on the Cycling Track in Ordrup",
      video: false,
      vote_average: 6,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/jS2BqYg8ZtjQnuxQw0px4jirdnE.jpg",
      genre_ids: [18, 10749],
      id: 1025438,
      original_language: "ja",
      original_title: "恋のいばら",
      overview:
        'After getting dumped by her boyfriend Kentaro, Tomita Momo, who works at a library, suddenly discovers the existence of her ex-boyfriend\'s current girlfriend Riko through his social media. She is intrigued by Riko, who is the opposite of herself in terms of fashionable sophistication. For "a certain reason," she goes to see Riko in person. Momo confronts Riko and asks, "Do you know what revenge porn is?" And "I want to get back the secret photo data of the two of us that he took... Also, haven\'t you been taken as well...". An ex-girlfriend and a current girlfriend. Now that these two unlikely lovers have met, their "secret complicity" is about to begin.',
      popularity: 1.864,
      poster_path: "/h45Pak8mLm2bIapwhlHjD2xkrQj.jpg",
      release_date: "2023-01-06",
      title: "Thorns of Love",
      video: false,
      vote_average: 8,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878, 27],
      id: 366914,
      original_language: "ja",
      original_title: "THORN",
      overview:
        "A high-school boy with telekinesis kills himself after being bullied and beaten by his classmates. The boy had been secretly storing his special power in his pet cactus. After the boy's death, the cactus is passed onto his mother who inherits his power and vows to avenge his death.",
      popularity: 0.935,
      poster_path: "/iv6hIk9fCLGoxFUIUgArmcoHB26.jpg",
      release_date: "2015-09-13",
      title: "Thorn",
      video: false,
      vote_average: 4.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 18],
      id: 76972,
      original_language: "ta",
      original_title: "தோரணை",
      overview:
        "A man comes to Chennai with a mission to find his brother, who had run away from his house about two decades ago. But a series of events make them both a part of unexpected happenings.",
      popularity: 2.903,
      poster_path: "/9LLqbWfJrXWBNM9PezVh55mMmIK.jpg",
      release_date: "2009-05-29",
      title: "Thoranai",
      video: false,
      vote_average: 4.7,
      vote_count: 11,
    },
    {
      adult: false,
      backdrop_path: "/905okdSHY5CcpcMmBchiVS3YOMj.jpg",
      genre_ids: [10749, 18],
      id: 482626,
      original_language: "ko",
      original_title: "까시",
      overview:
        "Jin-goo is tall and handsome. Sam-bong is short and ugly. The two go to the same university and live in a rooftop house in the country. One day, Jin-goo meets Se-ra who simply wants to be in his arms. She begs him to let her stay with him for a week as she has no where to go and the three of them live together.",
      popularity: 6.422,
      poster_path: "/d5tou1gbvDo9tTncb0qpoyNWd3y.jpg",
      release_date: "2016-10-27",
      title: "Thorn",
      video: false,
      vote_average: 4.3,
      vote_count: 5,
    },
  ],
  total_pages: 13,
  total_results: 243,
};
